### ISSUE TITLE
Remove noClasses option from breakpoints

### ISSUE THREAD

**Issue by OMMatte** [elqteam/elq#28]
noClasses is needed when elq-breakpoints and elq-mirror is used together, in order to ensure that only elq-mirror creates the breakpoints but elq-breakpoints is still the breakpoint for following elq-mirrors.
Since you always want this behaviour and it only happens when elq-breakpoints and elq-mirror are stated in the same element, then why not just detect this instead of forcing the user to remember the 'noClasses' option.
This will however probably force elq-breakpoints and elq-mirror to know about each other, or at least breakpoints to know about mirror. Which is related to issue #8 .

**Comment by wnr** [comment]
This has been fixed in 0.3.0
