### ISSUE TITLE
Drop elq-mirror as a default plugin?

### ISSUE THREAD

**Issue by AntonTrollback** [elqteam/elq#41]
I'm thinking it might be out of scope.

Tag-level selectors is somewhat of an anti-pattern. Large scale applications could/should either use some kind of javascript CSS scoping solution or a strict class based naming convention such as BEM or Suit CSS.

**Comment by wnr** [comment]
The mirror plugin is not limited to tag selectors, it's just a part of the API. Head over at https://github.com/elqteam/elq-grid/blob/master/src/js/feature/grid-handler.js#L76 to see the JavaScript API of this plugin.

I don't see how "a strict class based naming convention such as BEM or Suit CSS" can solve the problem of nesting responsive modules without a known structure. For example, the ```col-300px-5``` class, of the ```elq-grid``` plugin, can be put on any element in any context and is then expected to be relative to its nearest ```elq-breakpoints``` container.

"some kind of javascript CSS scoping solution" could perhaps be used, but I still think that it aims to solve another problem than the mirror does.

**Comment by wnr** [comment]
Now a couple of months later, I believe it is right to drop the default plugins. The usage of element queries seem varied enough to not bundle default plugins. Some only use the JS API of ELQ, which doesn't need the bundled plugins. This has also been discussed in this issue #46.

This is planned to #48

**Comment by wnr** [comment]
We now have a `dist/elq-without-plugins.js` that does not contain these plugins.
