### ISSUE TITLE
applyBreakpointStates?

### ISSUE THREAD

**Issue by kenborge** [elqteam/elq#47]
Does this method of the plugin API actually exist? It's never called and i can't find any reference to it in the code expect for the README

**Comment by wnr** [comment]
Whoops, you are right. Well spotted! :) That method is currently called `serializeBreakpointStates` in the code, but it was decided that it should be renamed to `applyBreakpointStates` instead. The docs and the code seems to have diverged. I think we should add support for both method names for now and deprecate the `serializeBreakpointStates` until version 2.0.0. What do you think?

**Comment by kenborge** [comment]
That sounds like a good solution
